// Generated by scripts/gen-beam-css.mjs from border-beam@1.3.0 (MIT, Jakub Antalik) with {"size":"md","colorVariant":"ocean","theme":"dark","borderRadius":16}. Do not edit.
// @property rules are ignored inside a shadow root; the bubble registers these on the document.
export const BEAM_PROPERTIES = [
  {
    "name": "--beam-angle-glance",
    "syntax": "<angle>",
    "initialValue": "0deg",
    "inherits": true
  },
  {
    "name": "--beam-opacity-glance",
    "syntax": "<number>",
    "initialValue": "0",
    "inherits": true
  }
] as const;
